// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27pj3JVQ9YFMxtz7Z2uJiEgz_TtQObCc',
    appId: '1:835596600741:web:e2b7a07d3ffc293735544c',
    messagingSenderId: '835596600741',
    projectId: 'recloset-99e15',
    authDomain: 'recloset-99e15.firebaseapp.com',
    storageBucket: 'recloset-99e15.appspot.com',
    measurementId: 'G-HH2M4M9NMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtUSO1cuUJplHr1c4raOosBCW5NH_xgw',
    appId: '1:835596600741:android:f12f180ca7cb344f35544c',
    messagingSenderId: '835596600741',
    projectId: 'recloset-99e15',
    storageBucket: 'recloset-99e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChENTyE7xQcJXIgoxjxvqV2XlRTFwSN-0',
    appId: '1:835596600741:ios:f989198bad21f94235544c',
    messagingSenderId: '835596600741',
    projectId: 'recloset-99e15',
    storageBucket: 'recloset-99e15.appspot.com',
    iosClientId: '835596600741-9qb9gbealdi8u34b788e1ufl7d2aviih.apps.googleusercontent.com',
    iosBundleId: 'com.reCloset.recloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChENTyE7xQcJXIgoxjxvqV2XlRTFwSN-0',
    appId: '1:835596600741:ios:f989198bad21f94235544c',
    messagingSenderId: '835596600741',
    projectId: 'recloset-99e15',
    storageBucket: 'recloset-99e15.appspot.com',
    iosClientId: '835596600741-9qb9gbealdi8u34b788e1ufl7d2aviih.apps.googleusercontent.com',
    iosBundleId: 'com.reCloset.recloset',
  );
}
